import Config

config :volt, server: [prefix: "/assets", watch_dirs: ["lib/"]]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :example, ExampleWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4005],
  check_origin: false,
  code_reloader: true,
  # Not :phoenix_replay: compiling a path dependency deletes this app's
  # consolidated protocols in Elixir 1.20.0-1.20.4 (elixir-lang/elixir#15727),
  # so every request would reconsolidate them and regenerate the colocated
  # hooks, which makes Volt reload the page. Restart the server to pick up
  # changes to the library until an Elixir release has the fix.
  reloadable_apps: [:example],
  debug_errors: true,
  secret_key_base: "B5k/fPcLUFF31abKOAoHjDRW/RVOIq+IKaKVNqGN6Z6i9vLtMnMg8sQjQ0NvS4/S"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :example, ExampleWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"lib/example_web/router\.ex$",
      ~r"lib/example_web/(controllers|live|components)/.*\.(ex|heex)$",
      ~r"lib/phoenix_replay/.*(ex|heex)$"
    ]
  ]

# Watch parent directory for phoenix_replay path dep changes
config :phoenix_live_reload, :dirs, ["", ".."]

# Enable dev routes for dashboard and mailbox
config :example, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
